//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EVOLUTION2022.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla
    {
        public int UsuId { get; set; }
        public string UsuNombre { get; set; }
        public string UsuPASS { get; set; }
    }
}
